### ISSUE TITLE
Missing finance_transaction_purchase_order in folio_reporting schema - v1.7.12

### ISSUE THREAD

**Issue by bbarnetteebsco** [folio-org/folio-analytics#876]
LDP version 2.1.0

Errors:
psql:tmpfile:70: ERROR:  relation "finance_transaction_purchase_order" does not exist
psql:tmpfile:71: ERROR:  operator does not exist: text = uuid
LINE 53: ...ion_invoices AS fintrainv ON fintrainv.invoice_id = inv.id A...
                                                              ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

May be related to similar issue: https://metadb-project.slack.com/archives/C03ETMG3TGX/p1737666971479769

**Comment by bbarnetteebsco** [comment]
@nassibnassar Hello sir, would be able to take a look? I think it may be similar to other issue mentioned in the issue.

**Comment by nassibnassar** [comment]
Fixed in v1.7.13

**Comment by bbarnetteebsco** [comment]
@nassibnassar we are still seeing some errors in the logs, although a bit different this time


psql:tmpfile:50: ERROR: relation "finance_transaction_purchase_order" does not exist
ERROR: column ft.expense_class_id does not exist
LINE 37: ...EFT JOIN finance_expense_classes AS ec ON ec.id = ft.expense...
psql:tmpfile:48: ERROR: relation "finance_transaction_purchase_order" does not exist
